sudo: required

services:
  - docker

arch:
  script:
    - "PKGEXT='.pkg.tar' makepkg -si --noconfirm"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
  email: false
